### ISSUE TITLE
Reports PowerPC and fails to load on M1 and above processors

### ISSUE THREAD

**Issue by justingeeslin** [CogTool-Modern/cogtool#69]

**Comment by justingeeslin** [comment]
Addressed this in the latest commits to master.

**Comment by justingeeslin** [comment]
Waiting to test on an M1 mac before I close this.

**Comment by justingeeslin** [comment]
Can confirm this is currently in `master`. 

```
2025-07-27 20:56:22.029 java[7696:42170286] The class 'NSOpenPanel' overrides the method identifier.  This method is implemented by class 'NSWindow'
Recovering...
edu.cmu.cs.hcii.cogtool.util.RcvrIllegalStateException: java.lang.IllegalStateException: CogTool no longers supports PowerPC
	at edu.cmu.cs.hcii.cogtool.controller.ComputePredictionCmd.computePrediction(ComputePredictionCmd.java:193)
	at edu.cmu.cs.hcii.cogtool.controller.ComputePredictionCmd.computePrediction(ComputePredictionCmd.java:168)
	at edu.cmu.cs.hcii.cogtool.controller.SEDemoController$26.performAction(SEDemoController.java:1844)
	at edu.cmu.cs.hcii.cogtool.util.ListenerIdentifierMap.performAction(ListenerIdentifierMap.java:216)
	at edu.cmu.cs.hcii.cogtool.util.ListenerIdentifierMap.performAction(ListenerIdentifierMap.java:267)
	at edu.cmu.cs.hcii.cogtool.ui.UI.performAction(UI.java:582)
	at edu.cmu.cs.hcii.cogtool.ui.UI.performAction(UI.java:552)
	at edu.cmu.cs.hcii.cogtool.ui.DefaultUI.performAction(DefaultUI.java:500)
	at edu.cmu.cs.hcii.cogtool.view.View.performAction(View.java:625)
	at edu.cmu.cs.hcii.cogtool.view.View$SWTWidgetChangeHandler.widgetSelected(View.java:197)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:286)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1657)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1680)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1665)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1394)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4427)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4003)
	at edu.cmu.cs.hcii.cogtool.util.WindowUtil.interact(WindowUtil.java:540)
	at edu.cmu.cs.hcii.cogtool.util.WindowUtil.interact(WindowUtil.java:570)
	at edu.cmu.cs.hcii.cogtool.CogTool.main(CogTool.java:378)
Caused by: java.lang.IllegalStateException: CogTool no longers supports PowerPC
	at edu.cmu.cs.hcii.cogtool.util.Subprocess.execLisp(Subprocess.java:441)
	at edu.cmu.cs.hcii.cogtool.model.ACTRPredictionAlgo$ACTRAnalysisInput.compute(ACTRPredictionAlgo.java:373)
	at edu.cmu.cs.hcii.cogtool.model.IPredictionAlgo$AAnalysisInput.compute(IPredictionAlgo.java:177)
	at edu.cmu.cs.hcii.cogtool.controller.ComputePredictionCmd.computePrediction(ComputePredictionCmd.java:184)
	... 21 more

```
